---

- debug:
    msg: "Tareas del 2do Parcial"

- name: Crear estructura de directorios 2do_parcial
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /tmp/2do_parcial/alumno
    - /tmp/2do_parcial/equipo

- name: Generar datos del alumno
  template:
    src: datos_alumno.txt.j2
    dest: /tmp/2do_parcial/alumno/datos_alumno.txt
    mode: '0644'

- name: Generar datos del equipo
  template:
    src: datos_equipo.txt.j2
    dest: /tmp/2do_parcial/equipo/datos_equipo.txt
    mode: '0644'

- name: Sudoers sin password para grupo 2PSupervisores
  become: yes
  lineinfile:
    path: /etc/sudoers.d/2psupervisores
    line: '%2PSupervisores ALL=(ALL) NOPASSWD: ALL'
    create: yes
    validate: 'visudo -cf %s'
    mode: '0440'
